use super::definition::{SyntaxDefinition, SyntaxMetadataSpec, SyntaxSpec, SyntaxTokenizer};
use super::error::SyntaxLoadError;

pub(super) fn builtin_syntax_definitions() -> Result<Vec<SyntaxDefinition>, SyntaxLoadError> {
    BUILTIN_SYNTAX_SPECS
        .iter()
        .map(SyntaxDefinition::from_spec)
        .collect()
}

static BUILTIN_SYNTAX_SPECS: &[SyntaxSpec] = &[
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "plaintext",
            display_name: "Plain Text",
            alias: &["text"],
            comment_prefix: None,
            glyph: None,
            glyph_color: None,
            filename: &[],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Plaintext,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "rust",
            display_name: "Rust",
            alias: &["rs"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e7a8}"),
            glyph_color: Some("#dea584"),
            filename: &["\\.rs$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Rust,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "python",
            display_name: "Python",
            alias: &["py"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e606}"),
            glyph_color: Some("#3572A5"),
            filename: &["\\.py$", "\\.pyw$"],
            shebang: &["^#!.*\\bpython(?:[0-9.]+)?(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Python,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "javascript",
            display_name: "JavaScript",
            alias: &["js"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e781}"),
            glyph_color: Some("#f1e05a"),
            filename: &["\\.(js|mjs|cjs|jsx)$"],
            shebang: &["^#!.*\\b(?:node(?:js)?|bun|deno)(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Javascript,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "typescript",
            display_name: "TypeScript",
            alias: &["ts"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e628}"),
            glyph_color: Some("#3178c6"),
            filename: &["\\.(ts|tsx)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Typescript,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "shell",
            display_name: "Shell",
            alias: &["sh"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e795}"),
            glyph_color: Some("#89e051"),
            filename: &["\\.sh$", "^procfile$"],
            shebang: &["^#!.*\\bsh(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Shell,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "bash",
            display_name: "Bash",
            alias: &["rbash"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e795}"),
            glyph_color: Some("#89e051"),
            filename: &["\\.bash$"],
            shebang: &["^#!.*\\bbash(?:\\s|$)", "^#!.*\\brbash(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Bash,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "zsh",
            display_name: "Zsh",
            alias: &["zshell"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e795}"),
            glyph_color: Some("#89e051"),
            filename: &["\\.zsh$"],
            shebang: &["^#!.*\\bzsh(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Zsh,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "fish",
            display_name: "Fish",
            alias: &["fish-shell"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e795}"),
            glyph_color: Some("#89e051"),
            filename: &["\\.fish$"],
            shebang: &["^#!.*\\bfish(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Fish,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "powershell",
            display_name: "PowerShell",
            alias: &["pwsh"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e795}"),
            glyph_color: Some("#5391fe"),
            filename: &["\\.(ps1|psm1|psd1)$"],
            shebang: &["^#!.*\\b(?:pwsh|powershell)(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Powershell,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "go",
            display_name: "Go",
            alias: &["golang"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e627}"),
            glyph_color: Some("#00ADD8"),
            filename: &["\\.go$"],
            shebang: &["^#!.*\\bgo(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Go,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "java",
            display_name: "Java",
            alias: &["jvm"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e738}"),
            glyph_color: Some("#b07219"),
            filename: &["\\.java$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Java,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "c",
            display_name: "C",
            alias: &["c89"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e61e}"),
            glyph_color: Some("#555555"),
            filename: &["\\.(c|h)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::C,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "cpp",
            display_name: "C++",
            alias: &["c++"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e61d}"),
            glyph_color: Some("#f34b7d"),
            filename: &["\\.(cc|cpp|cxx|hh|hpp|hxx)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Cpp,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "csharp",
            display_name: "C#",
            alias: &["cs"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e7a3}"),
            glyph_color: Some("#178600"),
            filename: &["\\.cs$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Csharp,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "ruby",
            display_name: "Ruby",
            alias: &["rb"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e791}"),
            glyph_color: Some("#701516"),
            filename: &["\\.rb$"],
            shebang: &["^#!.*\\bruby(?:[0-9.]+)?(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Ruby,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "php",
            display_name: "PHP",
            alias: &["php8"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e608}"),
            glyph_color: Some("#4F5D95"),
            filename: &["\\.php$"],
            shebang: &["^#!.*\\bphp(?:[0-9.]+)?(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Php,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "perl",
            display_name: "Perl",
            alias: &["pl"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e769}"),
            glyph_color: Some("#0298c3"),
            filename: &["\\.(pl|pm)$"],
            shebang: &["^#!.*\\bperl(?:[0-9.]+)?(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Perl,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "haskell",
            display_name: "Haskell",
            alias: &["hs"],
            comment_prefix: Some("--"),
            glyph: Some("\u{e777}"),
            glyph_color: Some("#5e5086"),
            filename: &["\\.hs$"],
            shebang: &["^#!.*\\b(?:ghci|runghc)(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Haskell,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "elixir",
            display_name: "Elixir",
            alias: &["ex"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e62d}"),
            glyph_color: Some("#6e4a7e"),
            filename: &["\\.(ex|exs)$"],
            shebang: &["^#!.*\\b(?:elixir|iex)(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Elixir,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "erlang",
            display_name: "Erlang",
            alias: &["erl"],
            comment_prefix: None,
            glyph: Some("\u{e7b1}"),
            glyph_color: Some("#b83998"),
            filename: &["\\.erl$"],
            shebang: &["^#!.*\\b(?:erl|escript)(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Erlang,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "ocaml",
            display_name: "OCaml",
            alias: &["ml"],
            comment_prefix: None,
            glyph: Some("\u{e67a}"),
            glyph_color: Some("#ef7a08"),
            filename: &["\\.(ml|mli)$"],
            shebang: &["^#!.*\\b(?:ocaml|utop)(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Ocaml,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "fsharp",
            display_name: "F#",
            alias: &["fs"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e7a7}"),
            glyph_color: Some("#b845fc"),
            filename: &["\\.(fs|fsi|fsx)$"],
            shebang: &["^#!.*\\b(?:fsharpi|fsi)(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Fsharp,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "kotlin",
            display_name: "Kotlin",
            alias: &["kt"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e634}"),
            glyph_color: Some("#A97BFF"),
            filename: &["\\.(kt|kts)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Kotlin,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "scala",
            display_name: "Scala",
            alias: &["sc"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e737}"),
            glyph_color: Some("#c22d40"),
            filename: &["\\.(scala|sc)$"],
            shebang: &["^#!.*\\bscala(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Scala,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "swift",
            display_name: "Swift",
            alias: &["swiftc"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e755}"),
            glyph_color: Some("#f05138"),
            filename: &["\\.swift$"],
            shebang: &["^#!.*\\bswift(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Swift,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "dart",
            display_name: "Dart",
            alias: &["dartlang"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e798}"),
            glyph_color: Some("#00B4AB"),
            filename: &["\\.dart$"],
            shebang: &["^#!.*\\bdart(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Dart,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "zig",
            display_name: "Zig",
            alias: &["ziglang"],
            comment_prefix: Some("//"),
            glyph: Some("\u{e6a9}"),
            glyph_color: Some("#f7a41d"),
            filename: &["\\.zig$"],
            shebang: &["^#!.*\\bzig(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Zig,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "nim",
            display_name: "Nim",
            alias: &["nimlang"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e677}"),
            glyph_color: Some("#ffc200"),
            filename: &["\\.nim$"],
            shebang: &["^#!.*\\bnim(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Nim,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "julia",
            display_name: "Julia",
            alias: &["jl"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e624}"),
            glyph_color: Some("#9558b2"),
            filename: &["\\.jl$"],
            shebang: &["^#!.*\\bjulia(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::Julia,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "r",
            display_name: "R",
            alias: &["rscript"],
            comment_prefix: Some("#"),
            glyph: Some("\u{f07d4}"),
            glyph_color: Some("#198CE7"),
            filename: &["\\.r$"],
            shebang: &["^#!.*\\brscript(?:\\s|$)"],
        },
        tokenizer: SyntaxTokenizer::R,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "markdown",
            display_name: "Markdown",
            alias: &["md"],
            comment_prefix: None,
            glyph: Some("\u{e609}"),
            glyph_color: Some("#083fa1"),
            filename: &["\\.(md|markdown)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Markdown,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "json",
            display_name: "JSON",
            alias: &["jsonc"],
            comment_prefix: None,
            glyph: Some("\u{e60b}"),
            glyph_color: Some("#cbcb41"),
            filename: &["\\.json$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Json,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "toml",
            display_name: "TOML",
            alias: &["tml"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e615}"),
            glyph_color: Some("#9c4221"),
            filename: &["\\.toml$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Toml,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "yaml",
            display_name: "YAML",
            alias: &["yml"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e615}"),
            glyph_color: Some("#cb171e"),
            filename: &["\\.(yaml|yml)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Yaml,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "html",
            display_name: "HTML",
            alias: &["htm"],
            comment_prefix: None,
            glyph: Some("\u{e60e}"),
            glyph_color: Some("#e34c26"),
            filename: &["\\.(html|htm)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Html,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "css",
            display_name: "CSS",
            alias: &["css3"],
            comment_prefix: None,
            glyph: Some("\u{e749}"),
            glyph_color: Some("#563d7c"),
            filename: &["\\.css$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Css,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "makefile",
            display_name: "Makefile",
            alias: &["make"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e779}"),
            glyph_color: Some("#427819"),
            filename: &["^(?:makefile|gnumakefile|mk)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Makefile,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "dockerfile",
            display_name: "Dockerfile",
            alias: &["docker"],
            comment_prefix: Some("#"),
            glyph: Some("\u{f308}"),
            glyph_color: Some("#2496ED"),
            filename: &["^dockerfile$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Dockerfile,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "cmake",
            display_name: "CMake",
            alias: &["cmakelists"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e794}"),
            glyph_color: Some("#064F8C"),
            filename: &["^(?:cmakelists\\.txt|cmake)$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Cmake,
    },
    SyntaxSpec {
        metadata: SyntaxMetadataSpec {
            name: "justfile",
            display_name: "Justfile",
            alias: &["just"],
            comment_prefix: Some("#"),
            glyph: Some("\u{e615}"),
            glyph_color: Some("#c92c2c"),
            filename: &["^justfile$"],
            shebang: &[],
        },
        tokenizer: SyntaxTokenizer::Justfile,
    },
];
