pub(super) fn builtin_syntax_sources() -> [(&'static str, &'static str); 41] {
    [
        ("plaintext.toml", include_str!("builtins/plaintext.toml")),
        ("rust.toml", include_str!("builtins/rust.toml")),
        ("python.toml", include_str!("builtins/python.toml")),
        ("javascript.toml", include_str!("builtins/javascript.toml")),
        ("typescript.toml", include_str!("builtins/typescript.toml")),
        ("shell.toml", include_str!("builtins/shell.toml")),
        ("bash.toml", include_str!("builtins/bash.toml")),
        ("zsh.toml", include_str!("builtins/zsh.toml")),
        ("fish.toml", include_str!("builtins/fish.toml")),
        ("powershell.toml", include_str!("builtins/powershell.toml")),
        ("go.toml", include_str!("builtins/go.toml")),
        ("java.toml", include_str!("builtins/java.toml")),
        ("c.toml", include_str!("builtins/c.toml")),
        ("cpp.toml", include_str!("builtins/cpp.toml")),
        ("csharp.toml", include_str!("builtins/csharp.toml")),
        ("ruby.toml", include_str!("builtins/ruby.toml")),
        ("php.toml", include_str!("builtins/php.toml")),
        ("perl.toml", include_str!("builtins/perl.toml")),
        ("haskell.toml", include_str!("builtins/haskell.toml")),
        ("elixir.toml", include_str!("builtins/elixir.toml")),
        ("erlang.toml", include_str!("builtins/erlang.toml")),
        ("ocaml.toml", include_str!("builtins/ocaml.toml")),
        ("fsharp.toml", include_str!("builtins/fsharp.toml")),
        ("kotlin.toml", include_str!("builtins/kotlin.toml")),
        ("scala.toml", include_str!("builtins/scala.toml")),
        ("swift.toml", include_str!("builtins/swift.toml")),
        ("dart.toml", include_str!("builtins/dart.toml")),
        ("zig.toml", include_str!("builtins/zig.toml")),
        ("nim.toml", include_str!("builtins/nim.toml")),
        ("julia.toml", include_str!("builtins/julia.toml")),
        ("r.toml", include_str!("builtins/r.toml")),
        ("markdown.toml", include_str!("builtins/markdown.toml")),
        ("json.toml", include_str!("builtins/json.toml")),
        ("toml.toml", include_str!("builtins/toml.toml")),
        ("yaml.toml", include_str!("builtins/yaml.toml")),
        ("html.toml", include_str!("builtins/html.toml")),
        ("css.toml", include_str!("builtins/css.toml")),
        ("makefile.toml", include_str!("builtins/makefile.toml")),
        ("dockerfile.toml", include_str!("builtins/dockerfile.toml")),
        ("cmake.toml", include_str!("builtins/cmake.toml")),
        ("justfile.toml", include_str!("builtins/justfile.toml")),
    ]
}
