[metadata]
name = "python"
display_name = "Python"
alias = ["py"]
filename = ["\\.py$", "\\.pyw$"]
shebang = ["^#!.*\\bpython(?:[0-9.]+)?(?:\\s|$)"]

[[rules]]
kind = "regex"
pattern = "#.*$"
tag = "comment"

[[rules]]
kind = "regex"
pattern = "^\\s*@[_A-Za-z][A-Za-z0-9_\\.]*\\b"
tag = "keyword"

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_fexpr_triple_double"], pop = ["py_fexpr_triple_double"], push = ["py_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_raw_fexpr_triple_double"], pop = ["py_raw_fexpr_triple_double"], push = ["py_raw_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "punctuation"
context = { requires = ["py_fexpr_double"], pop = ["py_fexpr_double"], push = ["py_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "punctuation"
context = { requires = ["py_raw_fexpr_double"], pop = ["py_raw_fexpr_double"], push = ["py_raw_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "punctuation"
context = { requires = ["py_fexpr_triple_double"], pop = ["py_fexpr_triple_double"], push = ["py_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "punctuation"
context = { requires = ["py_raw_fexpr_triple_double"], pop = ["py_raw_fexpr_triple_double"], push = ["py_raw_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_triple_double"], pop = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_raw_triple_double"], pop = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_ftriple_double"], pop = ["py_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_raw_ftriple_double"], pop = ["py_raw_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_fdouble"], pop = ["py_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_raw_fdouble"], pop = ["py_raw_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_double"], pop = ["py_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_raw_double"], pop = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "fr\"\"\""
tag = "string"
context = { push = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "rf\"\"\""
tag = "string"
context = { push = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "f\"\"\""
tag = "string"
context = { push = ["py_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "rb\"\"\""
tag = "string"
context = { push = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "br\"\"\""
tag = "string"
context = { push = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "r\"\"\""
tag = "string"
context = { push = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "b\"\"\""
tag = "string"
context = { push = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "u\"\"\""
tag = "string"
context = { push = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { push = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "fr\""
tag = "string"
context = { push = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "rf\""
tag = "string"
context = { push = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "f\""
tag = "string"
context = { push = ["py_fdouble"] }

[[rules]]
kind = "regex"
pattern = "rb\""
tag = "string"
context = { push = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "br\""
tag = "string"
context = { push = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "r\""
tag = "string"
context = { push = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "b\""
tag = "string"
context = { push = ["py_double"] }

[[rules]]
kind = "regex"
pattern = "u\""
tag = "string"
context = { push = ["py_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { push = ["py_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_triple_double"], pop = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\\\\."
tag = "punctuation"
context = { requires = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "[^\"\\\\]+"
tag = "string"
context = { requires = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\"\"\""
tag = "string"
context = { requires = ["py_raw_triple_double"], pop = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "[^\"]+"
tag = "string"
context = { requires = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_raw_triple_double"] }

[[rules]]
kind = "regex"
pattern = "\\{"
tag = "punctuation"
context = { requires = ["py_ftriple_double"], pop = ["py_ftriple_double"], push = ["py_fexpr_triple_double"] }

[[rules]]
kind = "regex"
pattern = "[^\"\\\\{]+"
tag = "string"
context = { requires = ["py_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\\{"
tag = "punctuation"
context = { requires = ["py_raw_ftriple_double"], pop = ["py_raw_ftriple_double"], push = ["py_raw_fexpr_triple_double"] }

[[rules]]
kind = "injection"
context = { requires = ["py_raw_fexpr_triple_double"] }
selector = { name = "python" }
fallback = "unstyled"

[[rules]]
kind = "regex"
pattern = "[^\"\\{]+"
tag = "string"
context = { requires = ["py_raw_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_raw_ftriple_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_double"], pop = ["py_double"] }

[[rules]]
kind = "regex"
pattern = "\\\\."
tag = "punctuation"
context = { requires = ["py_double"] }

[[rules]]
kind = "regex"
pattern = "[^\"\\\\]+"
tag = "string"
context = { requires = ["py_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_raw_double"], pop = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "[^\"]+"
tag = "string"
context = { requires = ["py_raw_double"] }

[[rules]]
kind = "regex"
pattern = "\""
tag = "string"
context = { requires = ["py_fdouble"], pop = ["py_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\\\\."
tag = "punctuation"
context = { requires = ["py_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\\{"
tag = "punctuation"
context = { requires = ["py_raw_fdouble"], pop = ["py_raw_fdouble"], push = ["py_raw_fexpr_double"] }

[[rules]]
kind = "injection"
context = { requires = ["py_raw_fexpr_double"] }
selector = { name = "python" }
fallback = "unstyled"

[[rules]]
kind = "regex"
pattern = "[^\"\\{]+"
tag = "string"
context = { requires = ["py_raw_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "string"
context = { requires = ["py_raw_fexpr_double"], pop = ["py_raw_fexpr_double"], push = ["py_raw_fdouble"] }

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "string"
context = { requires = ["py_fexpr_triple_double"], pop = ["py_fexpr_triple_double"], push = ["py_ftriple_double"] }

[[rules]]
kind = "injection"
context = { requires = ["py_fexpr_triple_double"] }
selector = { name = "python" }
fallback = "unstyled"

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "string"
context = { requires = ["py_raw_fexpr_triple_double"], pop = ["py_raw_fexpr_triple_double"], push = ["py_raw_ftriple_double"] }

[[rules]]
kind = "injection"
context = { requires = ["py_raw_fexpr_triple_double"] }
selector = { name = "python" }
fallback = "unstyled"

[[rules]]
kind = "regex"
pattern = "\\}"
tag = "string"
context = { requires = ["py_raw_fexpr_double"], pop = ["py_raw_fexpr_double"], push = ["py_raw_fdouble"] }

[[rules]]
kind = "injection"
context = { requires = ["py_raw_fexpr_double"] }
selector = { name = "python" }
fallback = "unstyled"

[[rules]]
kind = "regex"
pattern = "\\b(?:0[xX][0-9A-Fa-f](?:_?[0-9A-Fa-f])*(?:n)?|0[oO][0-7](?:_?[0-7])*(?:n)?|0[bB][01](?:_?[01])*(?:n)?|(?:\\d(?:_?\\d)*(?:\\.\\d(?:_?\\d)*)?|\\.\\d(?:_?\\d)*)(?:[eE][+-]?\\d(?:_?\\d)*)?(?:n)?)\\b"
tag = "number"

[[rules]]
kind = "regex"
pattern = "#[A-Za-z_][A-Za-z0-9_]*"
tag = "variable"

[[rules]]
kind = "regex"
pattern = "\\b(?:as|async|await|break|case|class|continue|def|del|elif|else|except|finally|for|from|if|import|in|is|lambda|match|nonlocal|pass|raise|return|try|type|while|with|yield)\\b"
tag = "keyword"

[[rules]]
kind = "regex"
pattern = "\\b(?:False|None|True)\\b"
tag = "constant"

[[rules]]
kind = "regex"
pattern = "\\b(?:Exception|TypeError|ValueError|int|float|str|list|dict|set|tuple|object|[A-Z][A-Za-z0-9_]*)\\b"
tag = "type"

[[rules]]
kind = "regex"
pattern = "\\b[$A-Za-z_][$A-Za-z0-9_]*\\b"
tag = "variable"

[[rules]]
kind = "regex"
pattern = "[(){}\\[\\],.:]"
tag = "punctuation"

[[rules]]
kind = "regex"
pattern = "(?:==|!=|<=|>=|:=|->|\\+\\+|--|[+\\-*/%=&|^~<>])"
tag = "operator"
